#+TITLE: Nerd Fonts Installer

This script is an installer for the awesome job made on [[https://github.com/ryanoasis/nerd-fonts][Nerd
Fonts]]. Nerd Fonts is a collection of over 50 patched fonts,
providing additional glyphs and icons for popular coding and
development tools.

For more information about Nerd Fonts and to explore the available
fonts, visit [[https://www.nerdfonts.com/][nerdfonts.com]].


*** Disclaimer

I do not own the fonts included in this installer. Each font has its
own license, which can be found in its respective repository on the
[[https://github.com/ryanoasis/nerd-fonts][Nerd Fonts GitHub page]].

~PLEASE~ select the fonts you agree with the licensing and comment the
ones you don't before downloading, as this is just a utility to
facilitate installation.

*** Dependencies

Before running the ~nerd-installer.sh~ script, make sure you have the
following dependencies installed on your system:

- ~bash~: The Bourne Again Shell, required to execute the script.
- ~wget~: Used to download the font files from the internet.
- ~unzip~: Used to extract the downloaded zip files.

You can install these dependencies using your system's package
manager. For example, on Debian-based systems like Ubuntu, you can
install them using the following commands:

#+BEGIN_SRC bash
sudo apt-get update
sudo apt-get install bash wget unzip
#+END_SRC

*** Usage

To use this installer, simply run the ~nerd-installer.sh~ script
provided in this repository. The script will download and install the
complete Nerd Fonts collection effortlessly.

#+BEGIN_SRC bash
./nerd-installer.sh
#+END_SRC

*** License

This script is licensed under the terms of the GNU General Public
License version 3.0. See the [[LICENSE][LICENSE]] file for more details.
